repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: pytest-all
        name: Run all tests
        entry: ./venv/bin/pytest tests/ -v --tb=short
        language: system
        pass_filenames: false
