repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: pytest-unit
        name: Run unit tests (excluding integration)
        entry: ./venv/bin/pytest tests/ --ignore=tests/integration/ -v --tb=short
        language: system
        pass_filenames: false
